# Generated by Django 5.2.17 on 2026-10-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_priceoffer'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='marketplace_provide_bb132e_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider', 'provider_payment_id'), name='unique_provider_reference'),
        ),
    ]
