# Generated by Django 5.2.17 on 2026-10-02 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_payment_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, help_text='When a staff member confirmed the UPI credit', null=True),
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('unmatched_count', models.PositiveIntegerField(default=0)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reconciliations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation',
            field=models.ForeignKey(blank=True, help_text='Bank statement this claim was matched against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='marketplace.reconciliation'),
        ),
    ]
