# Generated by Django 5.2.17 on 2026-10-02 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_email_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_route',
            field=models.CharField(choices=[('platform', 'Through the platform'), ('direct', 'Direct to the farmer')], default='platform', help_text='Direct transfers carry no platform fee', max_length=10),
        ),
        migrations.CreateModel(
            name='DemandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit the buyer hopes for (advisory, not binding)', max_digits=10, null=True)),
                ('delivery_city', models.CharField(max_length=150)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Grade, organic, packing, anything else')),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='marketplace.buyerprofile')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='marketplace.crop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='marketplace.buyerprofile')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='marketplace.farmerprofile')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='marketplace.order')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='marketplace.demandrequest')),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('upi', 'UPI ID (VPA)'), ('bank', 'Bank account')], default='upi', max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('account_holder', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=34)),
                ('ifsc', models.CharField(blank=True, max_length=11)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Set by staff after checking the bank/UPI account name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_route', models.CharField(choices=[('platform', 'Through the platform'), ('direct', 'Direct to the farmer')], default='platform', help_text="Seller's choice: take the money via the platform, or take it directly", max_length=10)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_offers', to='marketplace.farmerprofile')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_offer', to='marketplace.order')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.demandrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='demandrequest',
            index=models.Index(fields=['status', 'crop'], name='marketplace_status_c753f1_idx'),
        ),
        migrations.AddIndex(
            model_name='demandrequest',
            index=models.Index(fields=['-created_at'], name='marketplace_created_e4c53b_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('request', 'farmer'), name='unique_conversation_per_request_farmer'),
        ),
        migrations.AddConstraint(
            model_name='payoutmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user', 'kind'), name='one_primary_payout_method_per_kind'),
        ),
        migrations.AddIndex(
            model_name='requestoffer',
            index=models.Index(fields=['request', 'status'], name='marketplace_request_9d81e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('request', 'farmer'), name='unique_pending_offer_per_farmer'),
        ),
    ]
