# Generated by Django 5.2.17 on 2026-10-02 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_demand_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, help_text='Produce value owed to the farmer', max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Platform fee retained from these orders (informational)', max_digits=12)),
                ('delivery_amount', models.DecimalField(decimal_places=2, default=0, help_text="Delivery charges on these orders — not the farmer's money", max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, help_text='Manual corrections; negative values claw money back', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('method', models.CharField(blank=True, help_text='upi or bank', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Bank or gateway payout reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='marketplace.farmerprofile')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_item', to='marketplace.order')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.payout')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['farmer', 'status'], name='marketplace_farmer__f9d8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'period_end'], name='marketplace_status_acf72d_idx'),
        ),
    ]
