# Generated by Django 5.2.17 on 2026-10-02 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_payouts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payoutitem',
            options={'ordering': ['order_id', 'shipment_id']},
        ),
        migrations.AddField(
            model_name='payout',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, help_text='Set instead of a farmer when this statement pays a transporter', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='marketplace.deliverypartner'),
        ),
        migrations.AddField(
            model_name='payoutitem',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_item', to='marketplace.shipment'),
        ),
        migrations.AddField(
            model_name='payoutmethod',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, help_text='Set instead of a user when this pays a transporter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='marketplace.deliverypartner'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='marketplace.farmerprofile'),
        ),
        migrations.AlterField(
            model_name='payoutitem',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_item', to='marketplace.order'),
        ),
        migrations.AlterField(
            model_name='payoutmethod',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_partner__isnull', True), ('farmer__isnull', False)), models.Q(('delivery_partner__isnull', False), ('farmer__isnull', True)), _connector='OR'), name='payout_has_exactly_one_recipient'),
        ),
        migrations.AddConstraint(
            model_name='payoutitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('shipment__isnull', True)), models.Q(('order__isnull', True), ('shipment__isnull', False)), _connector='OR'), name='payoutitem_has_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='payoutmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('delivery_partner', 'kind'), name='one_primary_partner_payout_method_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='payoutmethod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_partner__isnull', True), ('user__isnull', False)), models.Q(('delivery_partner__isnull', False), ('user__isnull', True)), _connector='OR'), name='payoutmethod_has_exactly_one_owner'),
        ),
    ]
