# Generated by Django 5.2.17 on 2026-10-02 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_partner_payouts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('recorded', 'Recorded, awaiting buyer'), ('confirmed', 'Confirmed by both sides'), ('disputed', 'Disputed by the buyer')], default='recorded', max_length=20)),
                ('otp_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='proofs/%Y/%m')),
                ('signature', models.TextField(blank=True, help_text="SVG path data captured from the driver's finger")),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dispute_reason', models.CharField(blank=True, max_length=300)),
                ('confirmed_by_buyer', models.ForeignKey(blank=True, help_text='The buyer who accepted the delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_proofs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_proofs', to='marketplace.order')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_proofs', to='marketplace.deliverypartner')),
                ('recorded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_proofs', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proofs', to='marketplace.shipment')),
                ('stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='marketplace.shipmentstop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='marketplace_order_i_a41b89_idx'), models.Index(fields=['shipment', 'status'], name='marketplace_shipmen_8d0f7c_idx')],
            },
        ),
    ]
