# Generated by Django 5.2.17 on 2026-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_delivery_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('ok', 'OK'), ('warn', 'Warning'), ('fail', 'Failing')], default='ok', max_length=8)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('is_transition', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Service checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['name', '-checked_at'], name='marketplace_name_b43afc_idx')],
            },
        ),
    ]
