# Generated by Django 5.2.17 on 2026-10-03 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_service_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Set when the buyer started the thread from a listing instead of the board', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='marketplace.listing'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('listing', 'buyer'), name='unique_conversation_per_listing_buyer'),
        ),
    ]
