# Generated by Django 5.2.17 on 2026-10-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_listing_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='preferred_payment_route',
            field=models.CharField(choices=[('platform', 'Through the platform'), ('direct', 'Direct to the farmer')], default='platform', help_text='How buyers pay this farmer by default. Direct needs a UPI ID on file.', max_length=10),
        ),
    ]
